version: "3.8"

services:
  docker-go-trust:
    image: docker-go-trust:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - GO_TRUST_VERSION=main
    ports:
      - "6001:6001"
