version: "3.8"

services:
  go-trust-service:
    image: go-trust-service:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - GO_TRUST_VERSION=main
    ports:
      - "6001:6001"
